---
title: "HTO Report"
author: "Quanhu Sheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
---

```{r setup, include = FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE, include=TRUE, warning=FALSE, message=FALSE)
source('/home/shengq2/program/scDemultiplex_analysis/common.r')
knitr::opts_knit$set(root.dir = root_dir)
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r,eval=FALSE,echo=FALSE}
library(xfun)

source('/home/shengq2/program/scDemultiplex_analysis/common.r')

xfun::Rscript_call(
  rmarkdown::render,
  list(input="/home/shengq2/program/scDemultiplex_analysis/04_20230728_scDemultiplex_iteration.rmd",
       output_file=paste0(root_dir, get_date_str(), ".scDemultiplex_iteration.html")))
```

```{r results='asis'}
batch="batch2_c1"
for(batch in samples){
  batch_dir = paste0(root_dir, batch)
  prefix=paste0(batch_dir, "/scDemultiplex.0.001/", batch)
  detail<-read.csv(paste0(prefix, ".HTO.iteration.detail.csv"), row.names=1)
  
  ari<-read.csv(paste0(batch_dir, "/", batch, ".iteration.ari.csv"), row.names=1)
  fscore<-read.csv(paste0(batch_dir, "/", batch, ".iteration.fscore.csv"), row.names=1)

  cat("# ", batch, "\n\n")
  xnames = paste0('X', c(0:10))
  xnames = xnames[xnames %in% colnames(detail)]
  xi=1
  for(xi in c(1:(length(xnames)-1))){
    yi = xi+1
    xn = xnames[xi]
    yn = xnames[yi]
    x_ari = ari[xn,1]
    y_ari = ari[yn,1]
    x_fscore = fscore[xn,1]
    y_fscore = fscore[yn,1]
    
    cat(paste0("## ", xnames[xi], " to ", xnames[yi], "\n"))
    
    df<-data.frame("ARI"=c(x_ari, y_ari), "Fscore"=c(x_fscore, y_fscore))
    rownames(df) = c(xn, yn)
    
    tdf = data.frame(t(df))
    tdf$increase = tdf[,2] - tdf[,1]
    print(kable(tdf))
    
    move_tb = table(detail[,xn], detail[,yn])
    should_stop = scDemultiplex:::should_stop(detail[,xn], detail[,yn])
    
    cat("\nshould stop = ", should_stop, "\n")
    
    print(kable(move_tb))
  }
}

```