---
title: "scDemultiplex Refinement Report"
author: "Quanhu Sheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
---

```{r global options, include = FALSE}
knitr::opts_chunk$set(echo=FALSE, include=TRUE, warning=FALSE, message=FALSE)
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r,eval=FALSE,echo=FALSE}
library(xfun)

source('/home/shengq2/program/scDemultiplex_analysis/common.r')

xfun::Rscript_call(
  rmarkdown::render,
  list(input='/home/shengq2/program/scDemultiplex_analysis/06_20230728_check_refine_result.rmd',
       output_file=paste0(root_dir, get_date_str(), ".refine_result.html")))
```

```{r setup}
library(knitr)
library(kableExtra)

source("/home/shengq2/program/scDemultiplex_analysis/common.r")

get_color <- function(x){
  if (!grepl('[(]', x)) {
    return("black")
  }
  parts = unlist(strsplit(x, "(", fixed = TRUE))
  newv = as.numeric(parts[1])
  oldv = as.numeric(substring(parts[2], 1, nchar(parts[2])-1))
  if (newv > oldv) {
    return("red")
  } else if (newv < oldv) {
    return("blue")
  } else {
    return("black")
  }
}

get_row_color <- function(x){
  return(unlist(lapply(x, get_color)))
}

#x="0.267 (0.267)"
stopifnot("red" == get_color("0.667(0.46)"))
stopifnot("blue" == get_color("0.267(0.46)"))
stopifnot("black"== get_color("0.267(0.267)"))
stopifnot("black"== get_color("pbmc8"))

print_table <- function(csv_file, row.names=1){
  x <- read.csv(csv_file, row.names=row.names)
  x[x==""]<-"/"

  tbl <- x |>
    mutate_all(~ cell_spec(., format = "html", color = get_row_color(.), bold = FALSE)) |>
    kable(escape = FALSE) |>
    kable_classic(
      full_width = T,
      html_font = "Arial",
      font_size = 15
    )
  
  print(tbl)
}

```

# Adjusted Rand Index

```{r, echo=FALSE, results="asis"}
print_table(paste0(root_dir, "refine_ari.csv"))
```
Note: the number in brackets is the result using the approach alone. Red/blue indicates increased/decreased values after scDemultiplex refinement.

# F score

```{r, echo=FALSE, results="asis"}
print_table(paste0(root_dir, "refine_fscore.csv"))
```
Note: the number in brackets is the result using the approach alone. Red/blue indicates increased/decreased values after scDemultiplex refinement.
