---
title: "scDemultiplex ari/fscore report"
author: "Quanhu Sheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
---

```{r,eval=FALSE,echo=FALSE}
library(xfun)

source('/home/shengq2/program/scDemultiplex_analysis/common.r')

xfun::Rscript_call(
  rmarkdown::render,
  list(input="/home/shengq2/program/scDemultiplex_analysis/09_20230804_ari_fscore.rmd",
       output_file=paste0(root_dir, get_date_str(), ".ari_fscore.html")))
```

```{r setup, include = FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, results='asis')
source('/home/shengq2/program/scDemultiplex_analysis/common.r')
knitr::opts_knit$set(root.dir = root_dir)
```

```{r}
library(knitr)
library(kableExtra)
library(tidyverse)

print_highlight_table_by_column <- function(x){
  x <- x |> mutate(across(where(is.numeric), round, 3))
  
  no_genetic_hto<-x[rownames(x) != "genetic_HTO",]
  top2 = apply(no_genetic_hto, 2, function(x){
    sort(x, decreasing = T)[1:2]
  })
  first = top2[1,]
  second = top2[2,]

  tbl <- x |> 
    mutate(across(where(is.numeric), ~if_else(.x == first[cur_column()],
                               cell_spec(.x,format =  "html",color = "red", bold = TRUE), 
                               if_else(as.character(.x) == second[cur_column()],
                                       cell_spec(.x,format =  "html",color = "blue", bold = TRUE), 
                                       as.character(.x))))) |> 
    kable(escape = FALSE) |> 
    kable_classic(full_width = T, 
                  html_font = "Arial", 
                  font_size = 15)
  print(tbl)
}
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r results='asis'}
datalist = list()
sample="barnyard"
for(sample in samples){
  sample_dir = paste0(root_dir, sample)

  ari_csv=paste0(sample_dir, "/", sample, ".ari.csv")
  fscore_csv=paste0(sample_dir, "/", sample, ".fscore.csv")

  datalist[[sample]] = list(ari=read.csv(ari_csv, row.names=1), fscore=read.csv(fscore_csv, row.names=1))
}
```

# batch1

```{r}
df = cbind(datalist[["batch1_c1"]][["ari"]] , 
  datalist[["batch1_c2"]][["ari"]], 
  datalist[["batch1_c1"]][["fscore"]],
  datalist[["batch1_c2"]][["fscore"]])
colnames(df) = c("batch1_c1_ari", "batch1_c2_ari", "batch1_c1_fscore", "batch1_c2_fscore")

print_highlight_table_by_column(df)
```

# batch2

```{r}
df = cbind(datalist[["batch2_c1"]][["ari"]] , 
  datalist[["batch2_c2"]][["ari"]], 
  datalist[["batch2_c1"]][["fscore"]],
  datalist[["batch2_c2"]][["fscore"]])
colnames(df) = c("batch2_c1_ari", "batch2_c2_ari", "batch2_c1_fscore", "batch2_c2_fscore")

print_highlight_table_by_column(df)
```

# batch3

```{r}
df = cbind(datalist[["batch3_c1"]][["ari"]] , 
  datalist[["batch3_c2"]][["ari"]], 
  datalist[["batch3_c1"]][["fscore"]],
  datalist[["batch3_c2"]][["fscore"]])
colnames(df) = c("batch3_c1_ari", "batch3_c2_ari", "batch3_c1_fscore", "batch3_c2_fscore")

print_highlight_table_by_column(df)
```

# barnyard

```{r}
df = cbind(datalist[["barnyard"]][["ari"]] , 
  datalist[["barnyard"]][["fscore"]])

print_highlight_table_by_column(df)
```
# pbmc8

```{r}
df = cbind(datalist[["pbmc8"]][["ari"]] , 
  datalist[["pbmc8"]][["fscore"]])

print_highlight_table_by_column(df)
```
